version: "3"

services:
  deeper:
    volumes:
      - ./.:/root/Deeper:cached # <--- This will map ./py1 to /root/py1 inside the container.
    #image: tensorflow/tensorflow
    build: .
    #command: sh -c "pip install poetry && poetry install &&  poetry build"
    tty: true # Keep running
    # environment:
    #   - PORT=9000
    #   - FLASK_ENV=development
    #ports:
    #  - "9000:9000"
    working_dir: /root/Deeper
  #
  # development:
  #   image: tensorflow/tensorflow
  #   command: /usr/bash
  #   tty: true # Keep running
  #   #$ports:
  #   #  - "9000:9000"
  #   working_dir: /root/Deeper
  #   volumes:
  #     - ./.:/root/Deeper:cached # <--- This will map ./py1 to /root/py1 inside the container.
